# Apache Ignite module build pipeline
# Point to your docker repositoty
variables:
  DOCKER_HOST: "tcp://192.168.1.60:2375"

before_script:
  - pwd
  - mvn -v
  - printenv

stages:
  - deploy
  - deploy_public

deploy:
  stage: deploy
  only:
    - /^master.*$/
    - /^release.*$/
  script:
    # deploy ignite to internal repository
    - mvn clean deploy -Dignite.edition=apache-ignite-lgpl -Prelease,all-java,all-scala,licenses,lgpl,tensorflow,web-console,docker-image -DskipTests -Dmaven.javadoc.skip=true -DaltReleaseDeploymentRepository=hawkore.releases::default::http://nexus3:8081/repository/hawkore.releases/ -DaltSnapshotDeploymentRepository=hawkore.snapshots::default::http://nexus3:8081/repository/hawkore.snapshots/

deployPublic:
  stage: deploy_public
  only:
    - /^release.*$/
  script:
    # deploy ignite artifacts to public repository
    - mvn clean deploy -Dignite.edition=apache-ignite-lgpl -Prelease,all-java,all-scala,licenses,lgpl,tensorflow,web-console,docker-image -DskipTests -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -DaltReleaseDeploymentRepository=hawkore.releases::default::http://nexus3:8081/repository/hawkore-public.releases/
